apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-secret
  namespace: wordpress-jamf-test
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: jamf-cody-test
  MARIADB_DATABASE: jamf-test
  MARIADB_USER: jamf-cody
  MARIADB_PASSWORD: jamf-test-password
