apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo-app
resources:
  - 00-namespace-config.yaml
  - 01-database.yaml
  - 02-cache.yaml
  - 03-api.yaml
  - 04-frontend.yaml
  - 05-hpa.yaml
