apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mariadb.storage.size | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: {{ .Values.namespace }}
  labels:
    app: mariadb
spec:
  replicas: {{ .Values.mariadb.replicaCount }}
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: {{ .Values.mariadb.resources.requests.cpu | quote }}
              memory: {{ .Values.mariadb.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.mariadb.resources.limits.cpu | quote }}
              memory: {{ .Values.mariadb.resources.limits.memory | quote }}
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: MARIADB_ROOT_PASSWORD
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: MARIADB_DATABASE
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: MARIADB_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: MARIADB_PASSWORD
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: {{ .Values.namespace }}
  labels:
    app: mariadb
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb
