apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.auth.rootPassword | quote }}
  MARIADB_DATABASE: {{ .Values.mariadb.auth.database | quote }}
  MARIADB_USER: {{ .Values.mariadb.auth.username | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.auth.password | quote }}
